apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: safety-classifier-hpa
  namespace: safety-classifier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: safety-classifier
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safety-classifier-ingress
  namespace: safety-classifier
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "safety-classifier-ip"
    networking.gke.io/managed-certificates: "safety-classifier-ssl"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: safety-classifier.yourdomain.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: safety-classifier-service
            port:
              number: 80

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: safety-classifier-ssl
  namespace: safety-classifier
spec:
  domains:
  - safety-classifier.yourdomain.com