# Colab Pro optimized settings
# For environments without bitsandbytes GPU wheels, use smaller settings.
model:
  load_in_4bit: false

training:
  batch_size: 1
  gradient_accumulation_steps: 16
  max_seq_length: 128
  optim: "adamw_torch"

optimization:
  use_gradient_checkpointing: true
  clear_cache_steps: 50

# Stage 1 safety filter configuration for Colab
safety:
  enabled: false
  classifier_config_path: "../safety-text-classifier/configs/base_config.yaml"
  # Absolute path used in Colab after we unzip into /content/ml-learning/safety-text-classifier
  checkpoint_dir: "/content/ml-learning/safety-text-classifier/checkpoints/best_model"

# Dataset overrides for Colab
dataset:
  subset: "default"
